import type { AppData, GearItem } from "./types";

// Generated from the user's CSV gear list (키르). 164 items, with approximate KRW prices.

type SeedGear = Omit<GearItem, "addOnIds"> & { addOnIds?: string[] };

const gearSeed: SeedGear[] = [
  { id: "g1", name: "Gramless ultra 35L", brand: "Liteway", majorCategory: "BIG 4", minorCategory: "배낭", weightG: 360, quantity: 1, price: 250000 },
  { id: "g2", name: "Arc Haul 60L + belt pouch*2 (616+48g)", brand: "Zpacks", majorCategory: "BIG 4", minorCategory: "배낭", weightG: 664, quantity: 1, price: 520000 },
  { id: "g3", name: "X-Mid 1 Pro (+폴리크로)", brand: "Durston", majorCategory: "BIG 4", minorCategory: "텐트", weightG: 525, quantity: 1, price: 580000 },
  { id: "g4", name: "X-Dome 1+ (+폴리크로)", brand: "Durston", majorCategory: "BIG 4", minorCategory: "텐트", weightG: 1045, quantity: 1, price: 560000 },
  { id: "g5", name: "Radical 1 (+양면실리콘)", brand: "Samaya", majorCategory: "BIG 4", minorCategory: "텐트", weightG: 700, quantity: 1, price: 1200000 },
  { id: "g6", name: "에어 다운 블랭킷", brand: "Isuka", majorCategory: "BIG 4", minorCategory: "담요", weightG: 130, quantity: 1, price: 150000 },
  { id: "g7", name: "매직 100 13/10/-3", brand: "Cumulus", majorCategory: "BIG 4", minorCategory: "침낭", weightG: 220, quantity: 1, price: 300000 },
  { id: "g8", name: "X-Lite 200 (M) 8/3/-9", brand: "Cumulus", majorCategory: "BIG 4", minorCategory: "침낭", weightG: 350, quantity: 1, price: 420000 },
  { id: "g9", name: "울트라 0˚C (M) / 7/2/-13", brand: "Exped", majorCategory: "BIG 4", minorCategory: "침낭", weightG: 530, quantity: 1, price: 450000 },
  { id: "g10", name: "울트라 -10˚C (M) / -3/-9/-28", brand: "Exped", majorCategory: "BIG 4", minorCategory: "침낭", weightG: 995, quantity: 1, price: 650000 },
  { id: "g11", name: "롤매트 R (RV1.7)", brand: "Trailsgear", majorCategory: "BIG 4", minorCategory: "매트", weightG: 195, quantity: 1, price: 90000 },
  { id: "g12", name: "조르 S (RV2.3)", brand: "Nemo", majorCategory: "BIG 4", minorCategory: "매트", weightG: 295, quantity: 1, price: 120000 },
  { id: "g13", name: "오라 M (RV2.7)", brand: "Nemo", majorCategory: "BIG 4", minorCategory: "매트", weightG: 500, quantity: 1, price: 180000 },
  { id: "g14", name: "울트라스피어 R (RV4.3)", brand: "Rab", majorCategory: "BIG 4", minorCategory: "매트", weightG: 360, quantity: 1, price: 190000 },
  { id: "g15", name: "텐서 올시즌 RW (RV5.4)", brand: "Nemo", majorCategory: "BIG 4", minorCategory: "매트", weightG: 530, quantity: 1, price: 280000 },
  { id: "g16", name: "힙벨트", brand: "Cayl", majorCategory: "Add-Ons", minorCategory: "벨트", weightG: 108, quantity: 1, price: 40000 },
  { id: "g17", name: "백 에어 메쉬 패드 S", brand: "LunarProject", majorCategory: "Add-Ons", minorCategory: "패드", weightG: 75, quantity: 1, price: 30000 },
  { id: "g18", name: "럼버패드, 숄더패드", brand: "Zpacks", majorCategory: "Add-Ons", minorCategory: "패드", weightG: 50, quantity: 1, price: 40000 },
  { id: "g19", name: "숄더파우치 지퍼", brand: "Zpacks", majorCategory: "Add-Ons", minorCategory: "파우치", weightG: 22, quantity: 1, price: 35000 },
  { id: "g20", name: "숄더 보틀 파우치", brand: "Bonfus", majorCategory: "Add-Ons", minorCategory: "파우치", weightG: 13, quantity: 1, price: 30000 },
  { id: "g21", name: "보틀 홀더", brand: "HikerWksp", majorCategory: "Add-Ons", minorCategory: "파우치", weightG: 25, quantity: 1, price: 20000 },
  { id: "g22", name: "보틀파우치", brand: "Bayahro", majorCategory: "Add-Ons", minorCategory: "파우치", weightG: 44, quantity: 1, price: 25000 },
  { id: "g23", name: "다이니마 멀티파우치", brand: "Mysterywall", majorCategory: "Add-Ons", minorCategory: "파우치", weightG: 36, quantity: 1, price: 35000 },
  { id: "g24", name: "메쉬도어*2, 메쉬천장", brand: "Samaya", majorCategory: "Add-Ons", minorCategory: "악세서리", weightG: 146, quantity: 1, price: 150000 },
  { id: "g25", name: "마그네틱 도어 스토퍼", brand: "Custerv", majorCategory: "Add-Ons", minorCategory: "악세서리", weightG: 5, quantity: 1, price: 10000 },
  { id: "g26", name: "DAC 펙 세트 4+4EA", brand: "Durston", majorCategory: "Add-Ons", minorCategory: "펙", weightG: 92, quantity: 1, price: 25000 },
  { id: "g27", name: "DAC 펙 1EA", brand: "Helinox", majorCategory: "Add-Ons", minorCategory: "펙", weightG: 10, quantity: 8, price: 3000 },
  { id: "g28", name: "티타늄 스크류펙 8EA", brand: "SoulTrekker", majorCategory: "Add-Ons", minorCategory: "펙", weightG: 95, quantity: 1, price: 40000 },
  { id: "g29", name: "데크 앵커펙 8EA", majorCategory: "Add-Ons", minorCategory: "펙", weightG: 17, quantity: 1, price: 15000 },
  { id: "g30", name: "데크 나사펙 5EA", majorCategory: "Add-Ons", minorCategory: "펙", weightG: 5, quantity: 1, price: 10000 },
  { id: "g31", name: "트레일백 1EA", brand: "BlackDiamond", majorCategory: "Add-Ons", minorCategory: "트레킹폴", weightG: 240, quantity: 1, price: 80000, worn: true },
  { id: "g32", name: "카본 FLZ 폴 (110-125) 1EA", brand: "BlackDiamond", majorCategory: "Add-Ons", minorCategory: "트레킹폴", weightG: 153, quantity: 2, price: 120000, worn: true },
  { id: "g33", name: "백팩 라이너용 김장비닐 XL", majorCategory: "Add-Ons", minorCategory: "라이너", weightG: 64, quantity: 1, price: 1000, worn: true },
  { id: "g34", name: "미니 망치", brand: "Susa", majorCategory: "Add-Ons", minorCategory: "망치", weightG: 195, quantity: 1, price: 30000 },
  { id: "g35", name: "BRS-3000T (이소)", brand: "BRS", majorCategory: "화기 관련", minorCategory: "화기", weightG: 27, quantity: 1, price: 25000 },
  { id: "g36", name: "ST-340 (부탄)", brand: "Soto", majorCategory: "화기 관련", minorCategory: "화기", weightG: 360, quantity: 1, price: 70000 },
  { id: "g37", name: "Greenpeak 2", brand: "Firemaple", majorCategory: "화기 관련", minorCategory: "화기", weightG: 99, quantity: 1, price: 40000 },
  { id: "g38", name: "G2 팟", brand: "Firemaple", majorCategory: "화기 관련", minorCategory: "쿠커", weightG: 185, quantity: 1, price: 40000 },
  { id: "g39", name: "ACP-700 팟 (메쉬망 포함시 78g)", brand: "Arata", majorCategory: "화기 관련", minorCategory: "쿠커", weightG: 68, quantity: 1, price: 60000 },
  { id: "g40", name: "가스 지지대", brand: "Firemaple", majorCategory: "화기 관련", minorCategory: "지지대", weightG: 28, quantity: 1, price: 10000 },
  { id: "g41", name: "가스 지지대 미니", brand: "Wildsea", majorCategory: "화기 관련", minorCategory: "지지대", weightG: 8, quantity: 1, price: 8000 },
  { id: "g42", name: "편의점 똑딱이 라이터", majorCategory: "화기 관련", minorCategory: "라이터", weightG: 19, quantity: 1, price: 1000 },
  { id: "g43", name: "ST-486 가스라이터", brand: "Soto", majorCategory: "화기 관련", minorCategory: "라이터", weightG: 46, quantity: 1, price: 30000 },
  { id: "g44", name: "발열팩, 파우치, 쫄대 세트", brand: "Skan", majorCategory: "화기 관련", minorCategory: "비화식", weightG: 127, quantity: 1, price: 15000 },
  { id: "g45", name: "110g", majorCategory: "화기 관련", minorCategory: "이소가스", weightG: 210, quantity: 1, price: 6000 },
  { id: "g46", name: "230g", majorCategory: "화기 관련", minorCategory: "이소가스", weightG: 370, quantity: 1, price: 9000 },
  { id: "g47", name: "식수 100ml", majorCategory: "식수 용품", minorCategory: "물", weightG: 100, quantity: 10, consumable: true },
  { id: "g48", name: "퓨리스트 물병 650ml", brand: "Cayl", majorCategory: "식수 용품", minorCategory: "물병", weightG: 80, quantity: 1, price: 25000 },
  { id: "g49", name: "소프트 플라스크 500ml", brand: "BlackDiamond", majorCategory: "식수 용품", minorCategory: "물병", weightG: 68, quantity: 1, price: 20000 },
  { id: "g50", name: "파워오투 물병 500ml", majorCategory: "식수 용품", minorCategory: "물병", weightG: 35, quantity: 1, price: 5000 },
  { id: "g51", name: "Flex Water Pack 1L", brand: "Montbell", majorCategory: "식수 용품", minorCategory: "물병", weightG: 43, quantity: 1, price: 20000 },
  { id: "g52", name: "워터캐리 1.5L", brand: "Evernew", majorCategory: "식수 용품", minorCategory: "수낭", weightG: 36, quantity: 1, price: 25000 },
  { id: "g53", name: "ffx751 750ml", brand: "Thermos", majorCategory: "식수 용품", minorCategory: "보온병", weightG: 330, quantity: 1, price: 45000 },
  { id: "g54", name: "비프리 정수필터 + 물병 (35+37g)", brand: "Katadyn", majorCategory: "식수 용품", minorCategory: "정수필터", weightG: 72, quantity: 1, price: 50000 },
  { id: "g55", name: "퍼텍스 에어 패커블 자켓", brand: "Covernat", majorCategory: "의류", minorCategory: "소프트쉘", weightG: 135, quantity: 1, price: 100000, worn: true },
  { id: "g56", name: "패치워크 윈드쉘", brand: "AndWander", majorCategory: "의류", minorCategory: "소프트쉘", weightG: 309, quantity: 1, price: 300000, worn: true },
  { id: "g57", name: "다운포어 플러스 2.0", brand: "Rab", majorCategory: "의류", minorCategory: "하드쉘", weightG: 375, quantity: 1, price: 200000, worn: true },
  { id: "g58", name: "Men's Granite Crest Jacket (XS)", brand: "Patagonia", majorCategory: "의류", minorCategory: "하드쉘", weightG: 350, quantity: 1, price: 400000 },
  { id: "g59", name: "UL All weather Jacket (M)", brand: "Yamatomichi", majorCategory: "의류", minorCategory: "하드쉘", weightG: 161, quantity: 1, price: 350000, worn: true },
  { id: "g60", name: "Light Alpha Vest (M)", brand: "Cayl", majorCategory: "의류", minorCategory: "조끼", weightG: 83, quantity: 1, price: 120000, worn: true },
  { id: "g61", name: "델타 1/2집 후디", brand: "Arc'teryx", majorCategory: "의류", minorCategory: "미드레이어", weightG: 265, quantity: 1, price: 200000, worn: true },
  { id: "g62", name: "R1 Air Crewneck", brand: "Patagonia", majorCategory: "의류", minorCategory: "미드레이어", weightG: 255, quantity: 1, price: 160000, worn: true },
  { id: "g63", name: "AirMesh Hoody (M)", brand: "M.Hardwear", majorCategory: "의류", minorCategory: "미드레이어", weightG: 185, quantity: 1, price: 150000, worn: true },
  { id: "g64", name: "알파90 후디 M", brand: "Nonezero", majorCategory: "의류", minorCategory: "미드레이어", weightG: 134, quantity: 1, price: 150000, worn: true },
  { id: "g65", name: "알파60 후디 M", brand: ".neverthat", majorCategory: "의류", minorCategory: "미드레이어", weightG: 120, quantity: 1, price: 120000, worn: true },
  { id: "g66", name: "모스 알파90 크루넥", brand: "SierraDesign", majorCategory: "의류", minorCategory: "미드레이어", weightG: 100, quantity: 1, price: 90000, worn: true },
  { id: "g67", name: "모스 알파90 타이즈", brand: "SierraDesign", majorCategory: "의류", minorCategory: "미드레이어", weightG: 93, quantity: 1, price: 90000, worn: true },
  { id: "g68", name: "로 라이트웨이트 넥게이터", brand: "Arc'teryx", majorCategory: "의류", minorCategory: "악세서리", weightG: 52, quantity: 1, price: 50000, worn: true },
  { id: "g69", name: "지오라인 바라클라바", brand: "Montbell", majorCategory: "의류", minorCategory: "악세서리", weightG: 36, quantity: 1, price: 35000, worn: true },
  { id: "g70", name: "슈퍼써모 3/4 레깅스", brand: "Brynje", majorCategory: "의류", minorCategory: "베이스레이어", weightG: 123, quantity: 1, price: 90000, worn: true },
  { id: "g71", name: "여벌 이너세트", majorCategory: "의류", minorCategory: "베이스레이어", weightG: 185, quantity: 1, price: 30000 },
  { id: "g72", name: "콜드기어 레깅스", brand: "UnderArmour", majorCategory: "의류", minorCategory: "베이스레이어", weightG: 160, quantity: 1, price: 60000, worn: true },
  { id: "g73", name: "Torrid Jacket 10D/7D (S)", brand: "Enlightened E.", majorCategory: "의류", minorCategory: "합충자켓", weightG: 223, quantity: 1, price: 200000 },
  { id: "g74", name: "베이직 다운 팬츠 (M)", brand: "Cumulus", majorCategory: "의류", minorCategory: "우모바지", weightG: 184, quantity: 1, price: 200000 },
  { id: "g75", name: "아르곤팬츠 (M)", brand: "Rab", majorCategory: "의류", minorCategory: "우모바지", weightG: 350, quantity: 1, price: 250000 },
  { id: "g76", name: "수페리어 다운 자켓", brand: "Montbell", majorCategory: "의류", minorCategory: "우모복", weightG: 175, quantity: 1, price: 200000 },
  { id: "g77", name: "Hectogram '23 (95) (900fp, 260g)", brand: "BaseSleeping", majorCategory: "의류", minorCategory: "우모복", weightG: 435, quantity: 1, price: 400000 },
  { id: "g78", name: "프로텍션 부츠 (S)", brand: "Cumulus", majorCategory: "의류", minorCategory: "부티", weightG: 82, quantity: 1, price: 90000 },
  { id: "g79", name: "구스다운 부티", brand: "Joee", majorCategory: "의류", minorCategory: "부티", weightG: 140, quantity: 1, price: 60000 },
  { id: "g80", name: "알파120 양말", brand: "LightGearH.", majorCategory: "의류", minorCategory: "베이스레이어", weightG: 34, quantity: 1, price: 25000 },
  { id: "g81", name: "워드 헤드 토크", brand: "Arc'teryx", majorCategory: "의류", minorCategory: "비니", weightG: 74, quantity: 1, price: 50000, worn: true },
  { id: "g82", name: "심볼 울 비니", brand: "Samaya", majorCategory: "의류", minorCategory: "비니", weightG: 73, quantity: 1, price: 60000, worn: true },
  { id: "g83", name: "케나이 울 헤드밴드", brand: "SierraDesign", majorCategory: "의류", minorCategory: "헤드밴드", weightG: 73, quantity: 1, price: 30000, worn: true },
  { id: "g84", name: "메쉬 버킷햇", brand: "Cayl", majorCategory: "의류", minorCategory: "모자", weightG: 73, quantity: 1, price: 45000, worn: true },
  { id: "g85", name: "Light Mount cap", brand: "Cayl", majorCategory: "의류", minorCategory: "모자", weightG: 43, quantity: 1, price: 40000, worn: true },
  { id: "g86", name: "6P Cap", brand: "Parapack", majorCategory: "의류", minorCategory: "모자", weightG: 38, quantity: 1, price: 40000, worn: true },
  { id: "g87", name: "메쉬캡", brand: "Zerogram", majorCategory: "의류", minorCategory: "모자", weightG: 57, quantity: 1, price: 35000, worn: true },
  { id: "g88", name: "JQ Tape Cap", brand: "AndWander", majorCategory: "의류", minorCategory: "모자", weightG: 75, quantity: 1, price: 70000, worn: true },
  { id: "g89", name: "모스키토 헤드넷", brand: "SeatoSummit", majorCategory: "의류", minorCategory: "모자", weightG: 24, quantity: 1, price: 20000, worn: true },
  { id: "g90", name: "캐필린 미드웨이트 라이너 글러브즈", brand: "Patagonia", majorCategory: "의류", minorCategory: "장갑", weightG: 22, quantity: 1, price: 45000 },
  { id: "g91", name: "파워스트레치 콘택 그립 폴라텍", brand: "Rab", majorCategory: "의류", minorCategory: "장갑", weightG: 60, quantity: 1, price: 45000, worn: true },
  { id: "g92", name: "미션 LT 글러브", brand: "Blackdiamond", majorCategory: "의류", minorCategory: "장갑", weightG: 149, quantity: 1, price: 90000 },
  { id: "g93", name: "스포츠 타월", brand: "Chaoras", majorCategory: "의류", minorCategory: "타월", weightG: 47, quantity: 1, price: 15000, worn: true },
  { id: "g94", name: "퀵 드라이 타월", brand: "Naturehike", majorCategory: "의류", minorCategory: "타월", weightG: 40, quantity: 1, price: 10000 },
  { id: "g95", name: "EVA 슬리퍼", majorCategory: "의류", minorCategory: "신발", weightG: 140, quantity: 1, price: 15000 },
  { id: "g96", name: "접이식 폼 슬리퍼", brand: "LightGearH.", majorCategory: "의류", minorCategory: "신발", weightG: 120, quantity: 1, price: 30000 },
  { id: "g97", name: "아이자켓 리덕스", brand: "Oakly", majorCategory: "의류", minorCategory: "아이웨어", weightG: 35, quantity: 1, price: 200000 },
  { id: "g98", name: "안경/소프트파우치", brand: "Rawrow", majorCategory: "의류", minorCategory: "아이웨어", weightG: 14, quantity: 1, price: 150000 },
  { id: "g99", name: "Thru-hiker skirt N01", brand: "HHWgear", majorCategory: "의류", minorCategory: "레인웨어", weightG: 95, quantity: 1, price: 60000, worn: true },
  { id: "g100", name: "레인커버/우비치마", brand: "Burningkan", majorCategory: "의류", minorCategory: "레인웨어", weightG: 122, quantity: 1, price: 40000 },
  { id: "g101", name: "BPL 양실 우비치마", brand: "Burningkan", majorCategory: "의류", minorCategory: "레인웨어", weightG: 73, quantity: 1, price: 45000 },
  { id: "g102", name: "숏 스패츠", brand: "Burningkan", majorCategory: "의류", minorCategory: "스패츠", weightG: 40, quantity: 1, price: 30000 },
  { id: "g103", name: "일반적 1인분 식사", majorCategory: "음식", minorCategory: "음식", weightG: 250, quantity: 1, price: 8000, consumable: true },
  { id: "g104", name: "봉지라면", majorCategory: "음식", minorCategory: "음식", weightG: 140, quantity: 1, price: 1000, consumable: true },
  { id: "g105", name: "국밥류", majorCategory: "음식", minorCategory: "음식", weightG: 600, quantity: 1, price: 5000, consumable: true },
  { id: "g106", name: "라면애밥", majorCategory: "음식", minorCategory: "음식", weightG: 215, quantity: 1, price: 3000, consumable: true },
  { id: "g107", name: "컵스프", majorCategory: "음식", minorCategory: "음식", weightG: 20, quantity: 1, price: 2000, consumable: true },
  { id: "g108", name: "컵라면 큰 컵 (필요 물 400ml)", majorCategory: "음식", minorCategory: "음식", weightG: 120, quantity: 1, price: 1500, consumable: true },
  { id: "g109", name: "컵라면 작은 컵 (필요 물 265ml)", majorCategory: "음식", minorCategory: "음식", weightG: 65, quantity: 1, price: 1000, consumable: true },
  { id: "g110", name: "행동식/간식", majorCategory: "음식", minorCategory: "음식", weightG: 40, quantity: 3, price: 3000, consumable: true },
  { id: "g111", name: "전해질 알약", brand: "Yohemite", majorCategory: "음식", minorCategory: "보조제", weightG: 7, quantity: 3, price: 1000, consumable: true },
  { id: "g112", name: "크램프턴 에너지젤", brand: "Ollla", majorCategory: "음식", minorCategory: "보조제", weightG: 38, quantity: 2, price: 3000, consumable: true },
  { id: "g113", name: "가글, 치실", majorCategory: "위생/식기", minorCategory: "위생", weightG: 17, quantity: 1, price: 3000, consumable: true },
  { id: "g114", name: "칫솔, 미니치약", majorCategory: "위생/식기", minorCategory: "위생", weightG: 4, quantity: 1, price: 2000 },
  { id: "g115", name: "미니가위", majorCategory: "위생/식기", minorCategory: "위생", weightG: 14, quantity: 1, price: 3000 },
  { id: "g116", name: "샤워티슈", majorCategory: "위생/식기", minorCategory: "위생", weightG: 50, quantity: 1, price: 3000 },
  { id: "g117", name: "클렌징 패드", majorCategory: "위생/식기", minorCategory: "위생", weightG: 20, quantity: 1, price: 2000 },
  { id: "g118", name: "쓰레기봉투", majorCategory: "위생/식기", minorCategory: "위생", weightG: 1, quantity: 1, price: 1000 },
  { id: "g119", name: "상비약 세트", majorCategory: "위생/식기", minorCategory: "구급", weightG: 25, quantity: 1, price: 15000 },
  { id: "g120", name: "핫팩 일반크기", majorCategory: "위생/식기", minorCategory: "구급", weightG: 150, quantity: 1, price: 1000 },
  { id: "g121", name: "포켓 티슈", majorCategory: "위생/식기", minorCategory: "휴지", weightG: 19, quantity: 1, price: 1000 },
  { id: "g122", name: "티탄 싱글머그 300ml", brand: "Snowpeak", majorCategory: "위생/식기", minorCategory: "컵", weightG: 50, quantity: 1, price: 35000 },
  { id: "g123", name: "티탄 싱글머그 450ml", brand: "Snowpeak", majorCategory: "위생/식기", minorCategory: "컵", weightG: 64, quantity: 1, price: 40000 },
  { id: "g124", name: "폴딩컵 S", brand: "Wildo", majorCategory: "위생/식기", minorCategory: "컵", weightG: 24, quantity: 1, price: 8000 },
  { id: "g125", name: "폴딩컵 L", brand: "Wildo", majorCategory: "위생/식기", minorCategory: "컵", weightG: 46, quantity: 1, price: 10000 },
  { id: "g126", name: "숟가락칼/티타늄집게", brand: "Tritensil", majorCategory: "위생/식기", minorCategory: "커틀러리", weightG: 30, quantity: 1, price: 20000 },
  { id: "g127", name: "Nicktsucam 집게", brand: "Evernew", majorCategory: "위생/식기", minorCategory: "커틀러리", weightG: 9, quantity: 1, price: 25000 },
  { id: "g128", name: "티타늄 폴딩스푼", brand: "Tiartisan", majorCategory: "위생/식기", minorCategory: "커틀러리", weightG: 16, quantity: 1, price: 15000 },
  { id: "g129", name: "폴딩보울", brand: "Isemount", majorCategory: "위생/식기", minorCategory: "그릇", weightG: 26, quantity: 1, price: 20000 },
  { id: "g130", name: "미니 사각 팬", brand: "Topandtop", majorCategory: "위생/식기", minorCategory: "코펠", weightG: 218, quantity: 1, price: 30000 },
  { id: "g131", name: "메스틴 반합 L", brand: "Trangia", majorCategory: "위생/식기", minorCategory: "코펠", weightG: 170, quantity: 1, price: 30000 },
  { id: "g132", name: "필로 엘리트", brand: "Nemo", majorCategory: "전자/기타", minorCategory: "베개", weightG: 80, quantity: 1, price: 50000 },
  { id: "g133", name: "GR3x", brand: "Ricoh", majorCategory: "전자/기타", minorCategory: "카메라", weightG: 262, quantity: 1, price: 1300000 },
  { id: "g134", name: "DB-110 추가배터리", brand: "Ricoh", majorCategory: "전자/기타", minorCategory: "카메라", weightG: 40, quantity: 1, price: 40000 },
  { id: "g135", name: "fill x11 10000mAh / CtoC", brand: "Sky", majorCategory: "전자/기타", minorCategory: "보조배터리", weightG: 177, quantity: 1, price: 30000 },
  { id: "g136", name: "10000mAh / CtoC", brand: "Nextu", majorCategory: "전자/기타", minorCategory: "보조배터리", weightG: 165, quantity: 1, price: 25000 },
  { id: "g137", name: "도킹형 5000mAh", brand: "Actimon", majorCategory: "전자/기타", minorCategory: "보조배터리", weightG: 90, quantity: 1, price: 20000 },
  { id: "g138", name: "MicroSD 어댑터", brand: "Lenovo", majorCategory: "전자/기타", minorCategory: "OTG", weightG: 6, quantity: 1, price: 5000 },
  { id: "g139", name: "C to SD card 어댑터", brand: "Apple", majorCategory: "전자/기타", minorCategory: "OTG", weightG: 12, quantity: 1, price: 50000 },
  { id: "g140", name: "골제로 랜턴", brand: "Blackdog", majorCategory: "전자/기타", minorCategory: "조명", weightG: 75, quantity: 1, price: 30000 },
  { id: "g141", name: "캡온 40b", brand: "Claymore", majorCategory: "전자/기타", minorCategory: "조명", weightG: 25, quantity: 1, price: 30000 },
  { id: "g142", name: "헤디플러스", brand: "Claymore", majorCategory: "전자/기타", minorCategory: "조명", weightG: 110, quantity: 1, price: 50000 },
  { id: "g143", name: "랜턴", brand: "Dokeep", majorCategory: "전자/기타", minorCategory: "조명", weightG: 16, quantity: 2, price: 10000 },
  { id: "g144", name: "Nu25 UL", brand: "Nitecore", majorCategory: "전자/기타", minorCategory: "조명", weightG: 45, quantity: 1, price: 50000 },
  { id: "g145", name: "제로펌프", brand: "Flextail", majorCategory: "전자/기타", minorCategory: "펌프", weightG: 57, quantity: 1, price: 40000 },
  { id: "g146", name: "맥스펌프 3", brand: "Flextail", majorCategory: "전자/기타", minorCategory: "펌프", weightG: 122, quantity: 1, price: 50000 },
  { id: "g147", name: "스텐 스탠드", majorCategory: "전자/기타", minorCategory: "랜턴스탠드", weightG: 80, quantity: 1, price: 15000 },
  { id: "g148", name: "방수 디팩 M", brand: "Burningkan", majorCategory: "전자/기타", minorCategory: "디팩", weightG: 90, quantity: 1, price: 30000 },
  { id: "g149", name: "다이니마 드라이색", brand: "GWD", majorCategory: "전자/기타", minorCategory: "파우치", weightG: 22, quantity: 1, price: 30000 },
  { id: "g150", name: "다이니마 스터프색", brand: "GWD", majorCategory: "전자/기타", minorCategory: "파우치", weightG: 10, quantity: 1, price: 20000 },
  { id: "g151", name: "다이니마 랜턴쉐이드", brand: "HikerWksp", majorCategory: "전자/기타", minorCategory: "파우치", weightG: 5, quantity: 1, price: 15000 },
  { id: "g152", name: "다이니마 멀티캠 미니 파우치", majorCategory: "전자/기타", minorCategory: "파우치", weightG: 5, quantity: 1, price: 15000 },
  { id: "g153", name: "인슐레이트 보온보냉백 M", brand: "Bigsky", majorCategory: "전자/기타", minorCategory: "보냉백", weightG: 43, quantity: 1, price: 30000 },
  { id: "g154", name: "미니 경량우산", brand: "MUJI", majorCategory: "전자/기타", minorCategory: "우산", weightG: 118, quantity: 1, price: 20000 },
  { id: "g155", name: "카본 우산 + 부속품", brand: "LunaProject", majorCategory: "전자/기타", minorCategory: "우산", weightG: 155, quantity: 1, price: 90000 },
  { id: "g156", name: "체인젠 워크 L", brand: "Snowline", majorCategory: "전자/기타", minorCategory: "아이젠", weightG: 300, quantity: 1, price: 40000 },
  { id: "g157", name: "FR-CCR 카본체어", brand: "FieldRecord", majorCategory: "전자/기타", minorCategory: "체어", weightG: 270, quantity: 1, price: 250000 },
  { id: "g158", name: "체어제로", brand: "Helinox", majorCategory: "전자/기타", minorCategory: "체어", weightG: 510, quantity: 1, price: 150000 },
  { id: "g159", name: "Qwikback UL chair", brand: "LiteSmith", majorCategory: "전자/기타", minorCategory: "체어", weightG: 68, quantity: 1, price: 60000 },
  { id: "g160", name: "발포방석", brand: "Decathlon", majorCategory: "전자/기타", minorCategory: "방석", weightG: 60, quantity: 1, price: 5000 },
  { id: "g161", name: "UL테이블", brand: "SlowOutdoor", majorCategory: "전자/기타", minorCategory: "테이블", weightG: 64, quantity: 1, price: 60000 },
  { id: "g162", name: "울트라테이블 펜타", brand: "Lifesports", majorCategory: "전자/기타", minorCategory: "테이블", weightG: 825, quantity: 1, price: 50000 },
  { id: "g163", name: "1인용 눈썰매 스몰", majorCategory: "전자/기타", minorCategory: "썰매", weightG: 600, quantity: 1, price: 20000 },
  { id: "g164", name: "컴팩트 스노우 쇼블", brand: "Montbell", majorCategory: "전자/기타", minorCategory: "눈삽", weightG: 590, quantity: 1, price: 90000 },
];

const categoryOrder = ["BIG 4","Add-Ons","화기 관련","식수 용품","의류","음식","위생/식기","전자/기타"];

export function createSampleData(): AppData {
  const gear: Record<string, GearItem> = {};
  for (const g of gearSeed) gear[g.id] = { ...g, addOnIds: g.addOnIds ?? [] };
  return {
    gear,
    gearOrder: gearSeed.map((g) => g.id),
    categories: [...categoryOrder],
    presets: [],
    trips: {},
    tripOrder: [],
    displayUnit: "g",
    currency: "KRW",
    theme: "system",
  };
}
